Determine python and print it's info in --version

diff --git a/tahoe-i2p-install b/tahoe-i2p-install
--- a/tahoe-i2p-install
+++ b/tahoe-i2p-install
@@ -64,10 +64,6 @@ FOOLSCAP_DIR="${WORKING_DIR}/${FOOLSCAP_PKG:-foolscap-src}"
 TAHOE_DEPS_DIR="${WORKING_DIR}/tahoe-deps"
 TAHOE_LAFS_DIR="${WORKING_DIR}/${TAHOE_LAFS_PKG:-tahoe-lafs-src}"
 
-# If your python binary is named something else, set the correct
-# file name here
-PYTHON="python"
-
 if [ -f /etc/arch-release ]; then
     export PYCRYPTOPP_DISABLE_EMBEDDED_CRYPTOPP=1
 	if [ ! -e /sbin/ifconfig ]; then
@@ -78,6 +74,32 @@ if [ -f /etc/arch-release ]; then
 	fi
 fi
 
+PYTHON="python"
+PYTHON_VERSION=$($PYTHON --version 2>&1 | cut -d ' ' -f2 | cut -c 1-3)
+if [ $? = "0" ]; then
+	case $PYTHON_VERSION in
+		2.[5-7])
+			;;
+		3*)
+			echo "$PYTHON is not an acceptable version. Searching for suitable python2 version."
+		if [ `which python2.7 2> /dev/null` ]; then
+			PYTHON="python2.7"
+		elif [ `which python2.6 2> /dev/null` ]; then
+			PYTHON="python2.6"
+		elif [ `which python2.5 2> /dev/null` ]; then
+			PYTHON="python2.5"
+		elif [`which python2 2> /dev/null` ]; then
+			PYTHON="python2"
+		else
+			echo "Python2 not found. Aborting..."
+			exit 1
+		fi
+		;;
+	esac
+else
+	echo "Please install Python 2.5 <= 2.7, then rerun this script."
+	exit 1
+fi
 PYTHON_VERSION=$($PYTHON --version 2>&1 | cut -d ' ' -f2 | cut -c 1-3)
 
 # Detect sha256 checksum binary
@@ -449,6 +471,8 @@ while [[ $# > 0 ]] ; do
 	    echo "Downloads will be performed using $DOWNLOADWITH"
 	    echo "and checksums will be verified with"
 	    echo "$SHA256_BIN"
+	    echo
+	    echo "Python version $PYTHON_VERSION detected."
             exit 0 ;;
 
         -x|--no-fetch)
