Configurable PYTHON variable
The python variable will default to "python". If this binary is not a
python 2.5, 2.6, or 2.7 binary, alert the user.

diff --git a/tahoe-i2p-install b/tahoe-i2p-install
--- a/tahoe-i2p-install
+++ b/tahoe-i2p-install
@@ -74,8 +74,21 @@ if [ -f /etc/arch-release ]; then
         fi
 fi
 
-PYTHON="python"
+: ${PYTHON:="python"}
+export PYTHON
 PYTHON_VERSION=$($PYTHON --version 2>&1 | cut -d ' ' -f2 | cut -c 1-3)
+if [ $PYTHON_VERSION != "2.5" ] &&
+        [ $PYTHON_VERSION != "2.6" ] &&
+        [ $PYTHON_VERSION != "2.7" ]; then
+        echo "ERROR: Python $PYTHON_VERSION is not supported." >&2
+        echo >&2
+        echo "If you have Python 2.x on your system, set the environment" >&2
+        echo "variable PYTHON to the correct python binary." >&2
+        echo >&2
+        echo "For example, if the correct binary is called \"python2\"" >&2
+        echo "re-run this script with PYTHON=\"python2\" $0 $@" >&2
+        exit 1
+fi
 
 # Detect sha256 checksum binary
 
