indentation fixes

diff --git a/tahoe-i2p-install b/tahoe-i2p-install
--- a/tahoe-i2p-install
+++ b/tahoe-i2p-install
@@ -69,20 +69,20 @@ FOOLSCAP_DIR="${WORKING_DIR}/${FOOLSCAP_PKG:-foolscap-src}"
 TAHOE_DEPS_DIR="${WORKING_DIR}/tahoe-deps"
 TAHOE_LAFS_DIR="${WORKING_DIR}/${TAHOE_LAFS_PKG:-tahoe-lafs-src}"
 
-if [ -f /etc/arch-release ]; then
+if [ -e "/etc/arch-release" ]; then
     export PYCRYPTOPP_DISABLE_EMBEDDED_CRYPTOPP=1
-        if [ ! -e /sbin/ifconfig ]; then
-                echo "ERROR: The current version of Tahoe-LAFS requires ifconfig" >&2
-                echo "       and this tool is deprecated in ArchLinux. Please install" >&2
-                echo "       the net-tools package and re-run this script." >&2
-                exit 1
-        fi
+    if [ ! -e "/sbin/ifconfig" ]; then
+        echo "ERROR: The current version of Tahoe-LAFS requires ifconfig" >&2
+        echo "       and this tool is deprecated in ArchLinux. Please install" >&2
+        echo "       the net-tools package and re-run this script." >&2
+        exit 1
+    fi
     : ${PYTHON:="python2"}
 else
     : ${PYTHON:="python"}
 fi
-
 export PYTHON
+
 PYTHON_VERSION=$($PYTHON --version 2>&1 | cut -d ' ' -f2 | cut -c 1-3)
 if [ $PYTHON_VERSION != "2.5" ] &&
         [ $PYTHON_VERSION != "2.6" ] &&
