import of duck's 1.2 installer

diff --git a/tahoe-i2p-install b/tahoe-i2p-install
--- a/tahoe-i2p-install
+++ b/tahoe-i2p-install
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # tahoe-i2p-install - Install self-contained I2P mod of Tahoe-LAFS
 #
@@ -21,7 +21,7 @@
 
 # Release-specific metadata
 
-INSTALLER_VERSION="1.1"
+INSTALLER_VERSION="1.2.0"
 
 FOOLSCAP_VERSION="0.6.0"
 FOOLSCAP_PATCH_REVISION="r0"
@@ -64,6 +64,21 @@ TAHOE_DEPS_DIR="${WORKING_DIR}/tahoe-deps"
 TAHOE_LAFS_DIR="${WORKING_DIR}/${TAHOE_LAFS_PKG:-tahoe-lafs-src}"
 
 PYTHON_VERSION=$(python --version 2>&1 | cut -d ' ' -f2 | cut -c 1-3)
+
+# Detect sha256 checksum binary
+
+SHA256_BIN=`type -P sha256sum`
+if [[ $? -gt 0 ]] ; then
+    SHA256_BIN=`type -P sha256`
+    if [[ $? -eq 0 ]] ; then
+        SHA256_BIN="${SHA256_BIN} -r"
+    else
+        echo
+        echo "Error: Failed to locate sha256 checksum binary. Aborting." >&2
+        echo
+        exit 1
+    fi
+fi
 
 apply_patches() {
     echo
@@ -263,7 +278,8 @@ Options:
   -h, --help                  show usage information and exit
   -k, --keep-build-dirs       don't remove build directories when done
   -n, --no-proxy              don't use proxy for fetching [NOT anonymous!]
-  -p, --http_proxy ADDR:PORT  use the I2P HTTP proxy listening at address:port
+  -p, --http_proxy ADDR:PORT  use the I2P HTTP proxy listening on a
+                              non-default address:port
   -v, --version               show version information and exit
   -x, --no-fetch              do networkless install; don't download anything
 EOF
@@ -288,7 +304,7 @@ verify_hashes() {
     while [[ -n "$@" ]] ; do
         echo -n "${1} ... "
 
-        sha256=$(sha256sum "${1}" | cut -d ' ' -f1)
+        sha256=$(${SHA256_BIN} "${1}" | cut -d ' ' -f1)
 
         if [[ ${sha256} == ${2} ]] ; then
             echo "OK"
