Add  patching_failed and fetch_failed functions
These functions replace checks that don't work in sh.

diff --git a/tahoe-i2p-install b/tahoe-i2p-install
--- a/tahoe-i2p-install
+++ b/tahoe-i2p-install
@@ -130,6 +130,13 @@ else
     exit 1
 fi
 
+patching_failed() {
+    echo >&2
+    echo "Error: Failed to apply patch. Aborting." >&2
+    echo >&2
+    exit 1
+}
+
 apply_patches() {
     echo
     echo ">>> Patching sources"
@@ -143,14 +150,7 @@ apply_patches() {
 
         cd "${1}"
 
-        patch -p1 < "${WORKING_DIR}/${2}"
-
-        if [ $? -gt 0 ] ; then
-            echo >&2
-            echo "Error: Failed to apply patch. Aborting." >&2
-            echo >&2
-            exit 1
-        fi
+        patch -p1 < "${WORKING_DIR}/${2}" || patching_failed
 
         cd "$OLDPWD"
 
@@ -207,6 +207,16 @@ clean_build_dirs() {
     cd "$OLDPWD"
 }
 
+fetch_failed () {
+
+    echo >&2
+    echo "ERROR: Failed to download ${1}. Try fetching it manually and run" >&2
+    echo "       tahoe-i2p-install again. Aborting." >&2
+    echo >&2
+    exit 1
+}
+
+
 fetch_packages() {
     cd "${WORKING_DIR}"
 
@@ -219,36 +229,27 @@ fetch_packages() {
 
             if [ ${opt_no_proxy} ] ; then
                     if [ $DOWNLOADWITH = "wget" ]; then
-                            wget -c --no-proxy "${PATCH_HOME_WWW}/${p}"
+                            wget -c --no-proxy "${PATCH_HOME_WWW}/${p}" || fetch_failed patch
                     elif [ $DOWNLOADWITH = "fetch" ]; then
-                            fetch -a -m -d "${PATCH_HOME_WWW}/${p}"
+                            fetch -a -m -d "${PATCH_HOME_WWW}/${p}" || fetch_failed patch
                     elif [ $DOWNLOADWITH = "aria2c" ]; then
-                            aria2c --all-proxy "" "${PATCH_HOME_WWW}/${p}"
+                            aria2c --all-proxy "" "${PATCH_HOME_WWW}/${p}" || fetch_failed patch
                     else
                             echo; echo "Downloading ${PATCH_HOME_WWW}/${p}"
-                            curl -OL -x "" "${PATCH_HOME_WWW}/${p}"
+                            curl -OL -x "" "${PATCH_HOME_WWW}/${p}" || fetch_failed patch
                     fi
             else
                     if [ $DOWNLOADWITH = "wget" ]; then
-                            wget -c "${PATCH_HOME_I2P}/${p}"
+                            wget -c "${PATCH_HOME_I2P}/${p}" || fetch_failed patch
                     elif [ $DOWNLOADWITH = "fetch" ]; then
-                            fetch -a -m "${PATCH_HOME_I2P}/${p}"
+                            fetch -a -m "${PATCH_HOME_I2P}/${p}" || fetch_failed patch
                     elif [ $DOWNLOADWITH = "aria2c" ]; then
-                            aria2c "${PATCH_HOME_I2P}/${p}"
+                            aria2c "${PATCH_HOME_I2P}/${p}" || fetch_failed patch
                     else
                             echo; echo "Downloading from ${PATCH_HOME_I2P}/${p}"
-                            curl -OL "${PATCH_HOME_I2P}/${p}"
+                            curl -OL "${PATCH_HOME_I2P}/${p}" || fetch_failed patch
                     fi
             fi
-
-        if [ $? -gt 0 ] ; then
-            echo >&2
-            echo "Error: Failed to download patch. Try fetching it manually and run" >&2
-            echo "tahoe-i2p-install again. Aborting." >&2
-            echo >&2
-            exit 1
-        fi
-
     done
 
         if [ ${opt_no_proxy} ] ; then
@@ -263,22 +264,14 @@ fetch_packages() {
     while [ -n "${stack}" ]; do
 
         if [ $DOWNLOADWITH = "wget" ]; then
-                    wget -c "${1}/${2}${3}"
+                    wget -c "${1}/${2}${3}" || fetch_failed package
         elif [ $DOWNLOADWITH = "fetch" ]; then
-                    fetch -a -m "${1}/${2}${3}"
+                    fetch -a -m "${1}/${2}${3}" || fetch_failed package
         elif [ $DOWNLOADWITH = "aria2c" ]; then
-                    aria2c "${1}/${2}${3}"
+                    aria2c "${1}/${2}${3}" || fetch_failed package
         else
             echo; echo "Downloading from ${1}/${2}${3}"
-            curl -OL "${1}/${2}${3}"
-        fi
-
-        if [ $? -gt 0 ] ; then
-            echo >&2
-            echo "ERROR: Failed to download package. Try fetching it manually and run" >&2
-            echo "       tahoe-i2p-install again. Aborting." >&2
-            echo >&2
-            exit 1
+            curl -OL "${1}/${2}${3}" || fetch_failed package
         fi
 
         shift 3
