Show a warning if http*_proxy environment variables aren't I2P standard

diff --git a/tahoe-i2p-install b/tahoe-i2p-install
--- a/tahoe-i2p-install
+++ b/tahoe-i2p-install
@@ -463,12 +463,37 @@ while [[ $# > 0 ]] ; do
     esac
 done
 
-# Always start with clean build dirs
-clean_build_dirs
-
 : ${http_proxy:="127.0.0.1:4444"}
 : ${https_proxy:="127.0.0.1:4445"}
 export http_proxy https_proxy
+set -e
+
+trap 'echo;echo "CTRL+C keypress detected.";
+      echo "To use the default I2P Proxies you may call this script as";
+      echo "        http_proxy=\"\" https_proxy=\"\" $0 [options]";
+      echo' INT
+if [ $http_proxy != "127.0.0.1:4444" ] &&
+        [ $http_proxy != "localhost:4444" ]; then
+        echo "WARNING: Detected the following non-default environment variable(s)."
+        echo "         http_proxy: $http_proxy"
+        if [ $https_proxy != "127.0.0.1:4445" ] &&
+                [ $https_proxy != "localhost:4445" ]; then
+                echo  "         https_proxy: $https_proxy"
+                echo
+        fi
+        echo "If these are not I2P proxies, abort this script and set the"
+        echo "http*_proxy variables to point to your I2P proxies."
+        echo
+        echo "If these *are* I2P proxies, please wait 10 seconds and this"
+        echo "script will continue."
+        echo
+        sleep 10
+fi
+
+trap - INT TERM EXIT
+
+# Always start with clean build dirs
+clean_build_dirs
 
 [[ -z ${opt_no_fetch} ]] && fetch_packages
 
